/*
-- Query: SELECT * FROM transfusion_center.questionaires
LIMIT 0, 1000

-- Date: 2023-08-29 18:36
*/
USE transfusion_center;
INSERT INTO questionnaires (`id`,`termsAndConditions`,`description`,`title`, `type`) VALUES ('6cd6867f-6c5c-4d27-865f-e8bcac5b3c8b','I have filled in the Questionnaire for a donor of blood or blood components and I agree to donate blood or blood components and I declare:1) I have read and understood the educational material that I received and I declare under full responsibility that I answered all the questions correctly and entered correct data; 2) I have been informed that my blood will be tested for blood-borne diseases; 3) I was informed about the possibility to refuse to donate blood or blood components before the procedure, as well as the possibility of refusal to give, that is, the possibility of withdrawing consent at any time during the giving;  4) I have been informed about the purpose of donating blood or blood components;  5) I am familiar with the usual risks and possible reactions during blood collection, as well as the scope of blood testing; 6) I have been informed about the protection of personal data;  7) I had the opportunity to ask questions;  8) I received satisfactory answers to all the questions asked;   9) I have provided true information to the best of my knowledge; 10) I confirm the reliability of the given data. ','TO BE FILLED IN BY THE DONOR Please read the questionnaire and answer each question honestly. The questionnaire is important for the preservation of your health and the safety of transfusion treatment of patients. Your answers, as well as all other data about you, are completely confidential (medical secret) and will be used only for the needs of the authorized transfusion institution.','QUESTIONNAIRE FOR BLOOD OR BLOOD COMPONENT DONORS','Male');
INSERT INTO questionnaires (`id`,`termsAndConditions`,`description`,`title`, `type`) VALUES ('7380ba95-8813-44d0-b137-99462ec4dd0f','I have filled in the Questionnaire for a donor of blood or blood components and I agree to donate blood or blood components and I declare:1) I have read and understood the educational material that I received and I declare under full responsibility that I answered all the questions correctly and entered correct data; 2) I have been informed that my blood will be tested for blood-borne diseases; 3) I was informed about the possibility to refuse to donate blood or blood components before the procedure, as well as the possibility of refusal to give, that is, the possibility of withdrawing consent at any time during the giving;  4) I have been informed about the purpose of donating blood or blood components;  5) I am familiar with the usual risks and possible reactions during blood collection, as well as the scope of blood testing; 6) I have been informed about the protection of personal data;  7) I had the opportunity to ask questions;  8) I received satisfactory answers to all the questions asked;   9) I have provided true information to the best of my knowledge; 10) I confirm the reliability of the given data. ','TO BE FILLED IN BY THE DONOR Please read the questionnaire and answer each question honestly. The questionnaire is important for the preservation of your health and the safety of transfusion treatment of patients. Your answers, as well as all other data about you, are completely confidential (medical secret) and will be used only for the needs of the authorized transfusion institution.','QUESTIONNAIRE FOR BLOOD OR BLOOD COMPONENT DONORS','Female');
